import '../styles/globals.css'
import { Manrope } from 'next/font/google'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

export const metadata = {
  title: 'AudioExpressPro',
  description: 'Generated by create next app',
}

const manrope = Manrope({
  subsets: ['latin'],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.className} font-bold scroll-smooth`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
